from datetime import date, datetime
from src.models.movimentacao import Movimentacao
from sqlalchemy.ext.asyncio import AsyncSession

# Função para popular o banco de dados
async def inserir_dados(async_session: AsyncSession):

    def convert_date(date_str: str) -> date:
        return datetime.strptime(date_str, '%Y-%m-%d').date()

    try:
        async with async_session() as session:
            async with session.begin():
               session.add_all([Movimentacao(data_movimentacao=convert_date("2024-01-02"), numero_documento="21619", descricao="CRED PIX HORFRAN - NF-e 4453", tipo_operacao="Crédito", valor=260.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-03"), numero_documento="237", descricao="CRED TED BRASANITAS HOSPITALAR HIGIEN - NFS-e 2429 E NF-e 4443", tipo_operacao="Crédito", valor=585.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-05"), numero_documento="51237", descricao="ENVIO TEV ROBSON - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=2145.47, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-05"), numero_documento="51244", descricao="ENVIO PIX BRENDA - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=822.25, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-05"), numero_documento="51253", descricao="ENVIO PIX CINTHYA - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1353.37, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-05"), numero_documento="51256", descricao="ENVIO PIX NICOLAS - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1498.9, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-05"), numero_documento="51303", descricao="ENVIO PIX RONALDO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=957.88, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-05"), numero_documento="122023", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-08"), numero_documento="81520", descricao="PAG BOLETO ALUGUEL", tipo_operacao="Débito", valor=4708.01, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-08"), numero_documento="81524", descricao="PAG FGTS", tipo_operacao="Débito", valor=427.3, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-10"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA NFS-e 2450", tipo_operacao="Crédito", valor=7721.98, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-11"), numero_documento="111426", descricao="ENVIO PIX CINTHYA - PAGTO DE RESCISÃO", tipo_operacao="Débito", valor=1464.66, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-19"), numero_documento="191504", descricao="ENVIO PIX BRENDA - PAGTO ADIANTAMENTO DE SALÁRIO", tipo_operacao="Débito", valor=696.04, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-19"), numero_documento="191508", descricao="PG ORG GOV DARF ALUGUEL", tipo_operacao="Débito", valor=84.58, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-19"), numero_documento="191512", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1519.47, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-19"), numero_documento="191516", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=2767.23, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-22"), numero_documento="33", descricao="CRED TED DAIKIN AR CONDICIONADO BRASIL NFS-e 2458", tipo_operacao="Crédito", valor=300.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-22"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2457", tipo_operacao="Crédito", valor=6273.75, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-01-31"), numero_documento="290", descricao="CRED TED - PAGSEGURO INTERNET LTDA", tipo_operacao="Crédito", valor=2056.29, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-01"), numero_documento="237", descricao="CRED TED BRASANITAS HOSPITALAR HIGIEN NFS-e 2456 E NF-e 4459", tipo_operacao="Crédito", valor=1000.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-05"), numero_documento="52153", descricao="ENVIO PIX SILVIA - CONTABILIDADE HONORÁRIOS ", tipo_operacao="Débito", valor=789.45, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-05"), numero_documento="12024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-06"), numero_documento="61117", descricao="ENVIO TEV ROBSON - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=2334.11, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-06"), numero_documento="61124", descricao="ENVIO PIX NICOLAS - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1519.17, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-06"), numero_documento="61127", descricao="ENVIO PIX RONALDO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1500.28, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-06"), numero_documento="61131", descricao="ENVIO PIX THIAGO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1604.67, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-06"), numero_documento="61133", descricao="PAG FGTS", tipo_operacao="Débito", valor=1010.63, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-14"), numero_documento="341", descricao="CRED TED MONTEMOR INVESTIMENTOS E PARTI - NFS-e 2481", tipo_operacao="Crédito", valor=400.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-14"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA -NFS-e 2466", tipo_operacao="Crédito", valor=4037.37, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-15"), numero_documento="151507", descricao="PAG BOLETO CARTÃO AMERICAN", tipo_operacao="Débito", valor=1530.07, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-19"), numero_documento="191426", descricao="CRED PIX HORFRAN - COMERCIAL ELETRO MOVEIS LTDA NFS-e  2774", tipo_operacao="Crédito", valor=150.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-20"), numero_documento="201529", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=1858.81, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-20"), numero_documento="201532", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1413.92, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-20"), numero_documento="201535", descricao="ENVIO PIX LUIZ - ADIANTAMENTO QUINZENAL", tipo_operacao="Débito", valor=800.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-20"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2482", tipo_operacao="Crédito", valor=7061.32, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-20"), numero_documento="201546", descricao="PAG BOLETO CARTÃO INTER", tipo_operacao="Débito", valor=5275.53, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-21"), numero_documento="341", descricao="CRED TED FRESNOMAQ INDUSTRIA DE MAQUINA NFS-e 2478", tipo_operacao="Crédito", valor=2255.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-27"), numero_documento="271523", descricao="CRED PIX HORFRAN - COMERCIAL ELETRO MOVEIS LTDA NFS-e  2475", tipo_operacao="Crédito", valor=280.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-02-28"), numero_documento="281606", descricao="CRED PIX HORFRAN - COMERCIAL ELETRO MOVEIS LTDA NFS-e  4480", tipo_operacao="Crédito", valor=215.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-04"), numero_documento="422", descricao="CRED TED LOJAS COLOMBO NFS-e 2486", tipo_operacao="Crédito", valor=450.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-05"), numero_documento="22024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-06"), numero_documento="61206", descricao="ENVIO TEV ROBSON FERNANDES - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=2409.51, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-06"), numero_documento="290", descricao="CRED TED - PAGSEGURO INTERNET LTDA", tipo_operacao="Crédito", valor=483.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-06"), numero_documento="61518", descricao="ENVIO PIX RONALDO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1503.47, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-06"), numero_documento="61521", descricao="ENVIO PIX NICOLAS - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=632.24, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-06"), numero_documento="61607", descricao="ENVIO PIX LUIZ GUILHERME - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1301.87, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-06"), numero_documento="61611", descricao="PAG FGTS", tipo_operacao="Débito", valor=893.24, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-11"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA - NFS-e 2488", tipo_operacao="Crédito", valor=10131.6, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-15"), numero_documento="151710", descricao="PAG BOLETO PARANÁ CLINICAS", tipo_operacao="Débito", valor=1069.79, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-20"), numero_documento="201511", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=2414.58, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-20"), numero_documento="201514", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1298.23, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-20"), numero_documento="201521", descricao="PAG BOLETO CARTÃO INTER", tipo_operacao="Débito", valor=2799.92, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-20"), numero_documento="201552", descricao="ENVIO PIX LUIZ - ADIANTAMENTO QUINZENAL", tipo_operacao="Débito", valor=800.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-20"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2497", tipo_operacao="Crédito", valor=3231.24, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-03-25"), numero_documento="33", descricao="CRED TED DAIKIN AR CONDICIONADO BRASIL NFS-e 2499", tipo_operacao="Crédito", valor=150.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-05"), numero_documento="51257", descricao="ENVIO TEV ROBSON - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=2583.37, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-05"), numero_documento="32024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-08"), numero_documento="81454", descricao="ENVIO PIX ROBSON - PAGTO DE FÉRIAS", tipo_operacao="Débito", valor=1678.01, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-08"), numero_documento="81809", descricao="PAG BOLETO CIEE - ESTAGIÁRIO KAIO", tipo_operacao="Débito", valor=550.19, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-10"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA NFS-e 2506", tipo_operacao="Crédito", valor=7455.25, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-15"), numero_documento="151109", descricao="PAG BOLETO CARTÃO AMERICAN", tipo_operacao="Débito", valor=2070.26, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-17"), numero_documento="170102", descricao="CRED PIX MONTEMOR INVESTIMENTOS E PARTICIPACOES S A", tipo_operacao="Crédito", valor=480.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-19"), numero_documento="191217", descricao="ENVIO PIX LUIZ - PAGTO ADIANTAMENTO QUINZENAL", tipo_operacao="Débito", valor=838.88, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-19"), numero_documento="191228", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1477.01, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-19"), numero_documento="191744", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=1830.73, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-04-22"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2517", tipo_operacao="Crédito", valor=4545.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-03"), numero_documento="341", descricao="CRED TED FRESNOMAQ INDUSTRIA DE MAQUINA NFS-e 2518", tipo_operacao="Crédito", valor=1967.5, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-06"), numero_documento="61500", descricao="ENVIO PIX PAGTO HONORÁRIOS CONTABILIDADE", tipo_operacao="Débito", valor=559.45, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-06"), numero_documento="61722", descricao="ENVIO PIX SIMONE - PAGTO SERVIÇOS PRESTADO", tipo_operacao="Débito", valor=619.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-06"), numero_documento="42024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-07"), numero_documento="71219", descricao="ENVIO PIX LUIZ GUILHERME KRAUSE - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1476.99, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-07"), numero_documento="71223", descricao="ENVIO PIX ROBSON FERNANDES - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1058.62, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-07"), numero_documento="71833", descricao="ENVIO PIX ROBSON FERNANDES - COMPRA DE PLACA PARA TV ECEEL", tipo_operacao="Débito", valor=800.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-10"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA NFS-e 2524", tipo_operacao="Crédito", valor=12224.07, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-13"), numero_documento="131613", descricao="PAG BOLETO SPRINGER CARRIER", tipo_operacao="Débito", valor=214.88, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="237", descricao="CRED TED BRASANITAS HOSPITALAR HIGIEN -NFS 2495 E NF-e 4504", tipo_operacao="Crédito", valor=1200.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151612", descricao="PAG BOLETO PARANÁ CLINICAS - PLANOS SAÚDE", tipo_operacao="Débito", valor=1069.79, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151608", descricao="PAG BOLETO CARTÃO AMEX", tipo_operacao="Débito", valor=3281.19, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151616", descricao="ENVIO PIX CLAUDIO PRO-LABORE REF. À MARÇO C/ VENC EM ABRIL", tipo_operacao="Débito", valor=1352.8, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151618", descricao="ENVIO PIX ELISABETE PRO-LABORE REF. À MARÇO C/ VENC EM ABRIL", tipo_operacao="Débito", valor=1352.8, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151622", descricao="ENVIO PIX PAGTO ENERGIA LJ3", tipo_operacao="Débito", valor=162.14, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151626", descricao="ENVIO PIX PAGTO ENERGIA LJ4", tipo_operacao="Débito", valor=55.82, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151628", descricao="ENVIO PIX PAGTO ENERGIA LJ6", tipo_operacao="Débito", valor=380.19, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-15"), numero_documento="151742", descricao="CRED PIX HORFRAN - NFS-e 2483", tipo_operacao="Crédito", valor=180.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-16"), numero_documento="161618", descricao="CRED PIX HORFRAN - NF-e 4510", tipo_operacao="Crédito", valor=90.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="237", descricao="CRED TED BRASANITAS HOSPITALAR HIGIEN NFS-e 2494", tipo_operacao="Crédito", valor=450.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2534", tipo_operacao="Crédito", valor=11993.6, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="201615", descricao="ENVIO PIX LUIZ GUILHERME - PAGTO ADIANTAMENTO QUINZENAL", tipo_operacao="Débito", valor=838.88, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="201622", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1492.23, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="201627", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=2598.44, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="201632", descricao="ENVIO PIX FGTS", tipo_operacao="Débito", valor=1054.65, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="201651", descricao="ENVIO PIX GOVERNO DO PARANA - IPVA/2024 RANGER- 5 DE 5", tipo_operacao="Débito", valor=975.62, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-20"), numero_documento="201652", descricao="ENVIO PIX GOVERNO DO PARANA -IPVA/2024 FIESTA - 5 DE 5", tipo_operacao="Débito", valor=113.84, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-21"), numero_documento="211607", descricao="CRED PIX HORFRAN - NFS-e 2523 E NF-e 4548", tipo_operacao="Crédito", valor=380.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-22"), numero_documento="341", descricao="CRED TED FRESNOMAQ INDUSTRIA DE MAQUINA NFS-e 2531", tipo_operacao="Crédito", valor=3170.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-27"), numero_documento="422", descricao="CRED TED LOJAS COLOMBO - NFS-e 2541", tipo_operacao="Crédito", valor=110.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-27"), numero_documento="271638", descricao="CRED PIX HORFRAN - NFS-e 2538", tipo_operacao="Crédito", valor=280.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-28"), numero_documento="281049", descricao="CRED PIX HORFRAN - NFS-e 2536", tipo_operacao="Crédito", valor=100.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-29"), numero_documento="291631", descricao="CRED PIX HORFRAN - NF-e 4557", tipo_operacao="Crédito", valor=40.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-31"), numero_documento="311847", descricao="ENVIO PIX KAIO  SPURI LIMA - PAGTO DE VT ESTAGIÁRIO", tipo_operacao="Débito", valor=240.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-31"), numero_documento="311851", descricao="ENVIO PIX ELISABETE PRO-LABORE REF. À ABRIL C/ VENC EM MAIO", tipo_operacao="Débito", valor=1352.8, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-05-31"), numero_documento="311853", descricao="ENVIO PIX CLAUDIO PRO-LABORE REF. À ABRIL C/ VENC EM MAIO", tipo_operacao="Débito", valor=1352.8, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-03"), numero_documento="31523", descricao="PAG BOLETO SPRINGER CARRIER - 1 DE 2 PARCELAS", tipo_operacao="Débito", valor=376.66, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-03"), numero_documento="31529", descricao="ENVIO PIX GOVERNO DO PARANA SECRETARIA DE ESTADO DA FAZENDA-GRPR", tipo_operacao="Débito", valor=211.24, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-05"), numero_documento="51856", descricao="PAG CONTA DE ÁGUA", tipo_operacao="Débito", valor=226.75, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-05"), numero_documento="51859", descricao="ENVIO PIX SIMONE - SERVIÇOS PRESTADO", tipo_operacao="Débito", valor=577.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-05"), numero_documento="51903", descricao="ENVIO PIX PAGTO HONORÁRIOS CONTABILIDADE", tipo_operacao="Débito", valor=559.45, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-05"), numero_documento="52024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-06"), numero_documento="61200", descricao="ENVIO PIX JUAN V MARTINS - PAGTO VALE TRANSPORTE", tipo_operacao="Débito", valor=240.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-06"), numero_documento="61223", descricao="ENVIO TEV ROBSON FERNANDES - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=2436.31, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-06"), numero_documento="61237", descricao="ENVIO PIX LUIZ GUILHERME - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1561.73, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-06"), numero_documento="61240", descricao="ENVIO PIX NICOLAS - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1465.32, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-06"), numero_documento="61243", descricao="ENVIO PIX RONALDO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1642.34, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-07"), numero_documento="71531", descricao="PAG BOLETO CIEE - ESTAGIÁRIO", tipo_operacao="Débito", valor=550.19, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-10"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA - NFS-e 2543", tipo_operacao="Crédito", valor=7704.82, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-10"), numero_documento="101029", descricao="PAG BOLETO ALUGUEL", tipo_operacao="Débito", valor=4993.82, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-10"), numero_documento="101033", descricao="PAG BOLETO WHITE MARTINS", tipo_operacao="Débito", valor=48.42, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-10"), numero_documento="101036", descricao="PAG BOLETO REFRIGERAÇÃO DUFRIO", tipo_operacao="Débito", valor=311.22, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-14"), numero_documento="141953", descricao="PAG BOLETO CARTÃO AMERICAN", tipo_operacao="Débito", valor=2469.02, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-20"), numero_documento="201129", descricao="ENVIO PIX PAGTO FGTS", tipo_operacao="Débito", valor=1074.45, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-20"), numero_documento="201137", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=2683.2, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-20"), numero_documento="201141", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1485.73, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-20"), numero_documento="201205", descricao="PAG BOLETO SELETROAR - CONTRIBUIÇÃO ASSISTENCIAL DOS FUNCIONÁRIOS", tipo_operacao="Débito", valor=150.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-20"), numero_documento="201209", descricao="PAG BOLETO SPRINGER CARRIER NF 827546 - 1 DE 3", tipo_operacao="Débito", valor=428.12, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-20"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2554", tipo_operacao="Crédito", valor=5255.16, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-21"), numero_documento="341", descricao="CRED TED FRESNOMAQ INDUSTRIA DE MAQUINA NFS-e 2550", tipo_operacao="Crédito", valor=1365.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-26"), numero_documento="260927", descricao="ENVIO PIX LUIZ GUILHERME - PAGTO RESCISÃO DO CONTRATO DE TRABALHO", tipo_operacao="Débito", valor=2723.07, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-06-27"), numero_documento="270403", descricao="CRED PIX MAI TERRACES - NF-e 4583", tipo_operacao="Crédito", valor=1100.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-01"), numero_documento="11407", descricao="CRED PIX STONE PAGAMENTOS-MAQUININHA TON", tipo_operacao="Crédito", valor=1428.33, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-03"), numero_documento="31134", descricao="ENVIO PIX GOVERNO DO PARANA SECRETARIA DE ESTADO DA FAZENDA-GRPR", tipo_operacao="Débito", valor=657.14, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-03"), numero_documento="31627", descricao="CRED PIX HORFRAN - NF-e 4577 - NF-e 45 e NFS-e 2555", tipo_operacao="Crédito", valor=1250.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-05"), numero_documento="51134", descricao="   ENVIO TEV ROBSON FERNANDES - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=2806.33, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-05"), numero_documento="51139", descricao="ENVIO PIX RONALDO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1676.89, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-05"), numero_documento="51141", descricao="ENVIO PIX THIAGO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1625.1, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-05"), numero_documento="51144", descricao="ENVIO PIX PAGTO HONORÁRIOS CONTABILIDADE", tipo_operacao="Débito", valor=559.45, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-05"), numero_documento="62024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-10"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA - NFS-e 2569", tipo_operacao="Crédito", valor=6578.72, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-12"), numero_documento="121711", descricao="CRED TED PANASONIC DO BRASIL LIMITADA - NFS-e 2569", tipo_operacao="Crédito", valor=360.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-15"), numero_documento="150437", descricao="CRED PIX MAI TERRACES - NFS-e 2564", tipo_operacao="Crédito", valor=750.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-15"), numero_documento="151226", descricao="PAG BOLETO CARTÃO AMEX", tipo_operacao="Débito", valor=2646.03, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-15"), numero_documento="151228", descricao="ENVIO PIX CLAUDIO - PAGTO PRO-LABORE", tipo_operacao="Débito", valor=1352.8, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-17"), numero_documento="171443", descricao="CRED PIX HORFRAN - NFS-e 2573 E NF-e 4591", tipo_operacao="Crédito", valor=760.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-19"), numero_documento="191518", descricao="ENVIO PIX PAGTO FGTS", tipo_operacao="Débito", valor=1019.84, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-19"), numero_documento="191525", descricao="PG ORG GOV DARF/INSS", tipo_operacao="Débito", valor=1464.58, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-19"), numero_documento="191529", descricao="PG ORG GOV DAS", tipo_operacao="Débito", valor=2131.88, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-22"), numero_documento="341", descricao="CRED TED SPRINGER CARRIER LTDA NFS-e 2582", tipo_operacao="Crédito", valor=7481.22, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-22"), numero_documento="341", descricao="CRED TED FRESNOMAQ INDUSTRIA DE MAQUINA NFS-e 2578", tipo_operacao="Crédito", valor=2082.27, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-25"), numero_documento="251943", descricao="ENVIO PIX ELISABETE - PAGTO PRO-LABORE", tipo_operacao="Débito", valor=1352.8, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-26"), numero_documento="261713", descricao="ENVIO PIX TYFFANNE - PAGTO DE RESCISÃO DE CONTRATO", tipo_operacao="Débito", valor=426.81, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-29"), numero_documento="291525", descricao="CRED PIX HORFRAN - NFS-e 2584", tipo_operacao="Crédito", valor=180.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-07-30"), numero_documento="301511", descricao="CRED PIX HORFRAN - NF-e 4609", tipo_operacao="Crédito", valor=95.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-02"), numero_documento="20940", descricao="PAG BOLETO URBS - VALE TRANSPORTE - MARCOS", tipo_operacao="Débito", valor=267.03, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-05"), numero_documento="51139", descricao="ENVIO PIX PAGTO CONTA DE ÁGUA", tipo_operacao="Débito", valor=232.24, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-05"), numero_documento="51141", descricao="ENVIO PIX GOVERNO DO PARANA SECRETARIA DE ESTADO DA FAZENDA-GRPR", tipo_operacao="Débito", valor=633.12, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-05"), numero_documento="51153", descricao="ENVIO PIX PAGTO HONORÁRIOS CONTABILIDADE", tipo_operacao="Débito", valor=559.45, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-05"), numero_documento="72024", descricao="DB CEST PJ", tipo_operacao="Débito", valor=69.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-06"), numero_documento="61033", descricao="ENVIO PIX NICOLAS - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1645.26, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-06"), numero_documento="61038", descricao="ENVIO PIX THIAGO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1617.1, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-06"), numero_documento="61041", descricao="ENVIO PIX RONALDO - PAGTO DE SALÁRIO", tipo_operacao="Débito", valor=1726.23, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-07"), numero_documento="71627", descricao="PAG BOLETO VR BENEFICIOS E SERV. DE PROC. - P/ MARCOS", tipo_operacao="Débito", valor=200.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-07"), numero_documento="71632", descricao="ENVIO PIX ROBSON-REEMBOLSO DE DESPESAS C/ COMBUSTÍVEL E ALIM. REF. HORAS EXTRAS", tipo_operacao="Débito", valor=245.0, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-09"), numero_documento="91131", descricao="PAG BOLETO CIEE - PAGTO ESTAGIÁRIO KAIO", tipo_operacao="Débito", valor=550.19, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-12"), numero_documento="121509", descricao="PAG BOLETO CARTÃO PORTO SEGURO - PEDÁGIOS", tipo_operacao="Débito", valor=114.73, banco="CAIXA"),
                    Movimentacao(data_movimentacao=convert_date("2024-08-12"), numero_documento="341", descricao="CRED TED PANASONIC DO BRASIL LIMITADA - NFS-e 2585", tipo_operacao="Crédito", valor=2990.95, banco="CAIXA"),
                    ])
            await session.commit()
            print("Dados inseridos com sucesso!")
    except Exception as e:
        print(f"Erro ao inserir dados: {str(e)}")
        await session.rollback()
        raise  # Re-lança a exceção para não silenciar o erro